version: "2"

services:
  kurento:
    image: kurento/kurento-media-server:7.0.0
    ports:
      - "8888:8888"
    networks:
      - backend

  db:
    image: mariadb:10.6.16
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=openmeetings
      - MYSQL_PASSWORD=openmeetings
      - MYSQL_DATABASE=openmeetings      
    volumes:
      #- /home/user/project:/var/lib/mysql 
      - my-datavolume:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend

  openmeetings:
    # volumes:
    #   - /home/user/project5:/var/lib/mysql 
    #build: .
    #image: apache/openmeetings:7.2.0
    image: apache/openmeetings:min-7.2.0
    environment:
      - OM_KURENTO_WS_URL=ws://kurento:8888/kurento
      - OM_DB_TYPE=mysql
      - OM_DB_HOST=db
      - OM_DB_PORT=3306
      - OM_DB_USER=openmeetings
      - OM_DB_PASS=openmeetings
      - OM_DB_NAME=openmeetings

    ports:
      - "5443:5443"   
      - "5080:5080"   

    depends_on:
       - db
       - kurento
    networks:
      - backend

  # volumes:
  #       - my-datavolume:/var/lib/mysql
  # networks:
  #  my-net:
  #    ipv4_address: 95.84.169.33

volumes:
  my-datavolume: 

networks:
  # backend:
  #   driver: bridge

  backend:
    driver: macvlan
    driver_opts:
      parent: enp0s8
    ipam:
      config:
        - subnet: "192.168.56.101/24"
          gateway: "192.168.56.1"
          # aux_addresses:
          #     host: 95.84.169.179
